CREATE DATABASE Developer
USE Developer

CREATE TABLE Employee(
Id int primary key identity,
Fullname nvarchar(255) NOT NULL,
Age int CHECK(Age>0) NOT NULL,
Email nvarchar(255) UNIQUE,
Salary float NOT NULL  CHECK (SALARY >300 AND SALARY<2000),
)



INSERT INTO Employee VALUES('Taghizade Gulchin',20, 'gulcin.tagizade@gmail.com',1000)
INSERT INTO Employee VALUES('Taghizade Ilahe',19, 'Ilahe.tagizade@gmail.com',1700)
INSERT INTO Employee VALUES('Memmedov Abbas',18, 'abbas.memmedov@gmail.com',400)


SELECT *FROM Employee

UPDATE Employee
SET Salary=1500
WHERE Id=1


SELECT*FROM Employee WHERE Salary BETWEEN 500 AND 1000

SELECT Fullname, Email, Salary FROM Employee ORDER BY  SALARY DESC







CREATE DATABASE SCHOOL

CREATE TABLE STUDENTS(
ID INT PRIMARY KEY IDENTITY,
[NAME] NVARCHAR(50) NOT NULL,
SURNAME NVARCHAR(50),
PHONE NVARCHAR(20) UNIQUE,
SCORE INT DEFAULT(50),
COMMENT NVARCHAR(200),
ISGRADUATED BIT DEFAULT('FALSE')
)

INSERT INTO STUDENTS VALUES('GULCHIN','TAGHIZADE','+994775076266',97,'COMPUTER SCIENCE STUDENT','FALSE')
INSERT INTO STUDENTS VALUES('ILAHE','TAGHIZADE','+994775076166',90,'FINANCE STUDENT','FALSE')
INSERT INTO STUDENTS VALUES('NAIL','TAGHIZADE','+994775706266',60,'COMPUTER ENGINEERING STUDENT','TRUE')



SELECT * FROM STUDENTS

UPDATE STUDENTS
SET COMMENT='CONGRATULATIONS'
WHERE SCORE>(SELECT AVG(SCORE) FROM STUDENTS)

UPDATE STUDENTS
SET COMMENT='SO BAD'
WHERE SCORE<(SELECT AVG(SCORE) FROM STUDENTS)


CREATE TABLE GRADUATEDSTUDENTS(
ID INT,
[NAME] NVARCHAR(50),
SURNAME NVARCHAR(50),
PHONE NVARCHAR(20) UNIQUE,
SCORE INT DEFAULT(50),
COMMENT NVARCHAR(200),
ISGRADUATED BIT DEFAULT('FALSE') 
)



INSERT INTO GRADUATEDSTUDENTS 
SELECT * FROM STUDENTS
WHERE ISGRADUATED=1

SELECT * FROM GRADUATEDSTUDENTS

DELETE FROM STUDENTS WHERE ISGRADUATED=1






----------------------------------------

CREATE DATABASE TEST
USE TEST

CREATE TABLE VEZIFE(
ID INT PRIMARY KEY IDENTITY,
VEZIFE NVARCHAR(50)
)

CREATE TABLE ISCI(
ID INT PRIMARY KEY IDENTITY,
MKOD INT UNIQUE,
SAA NVARCHAR(200),
VEZIFEID INT REFERENCES VEZIFE(ID),
MAAS INT
)

CREATE TABLE FILIAL(
ID INT PRIMARY KEY IDENTITY,
FILIAL NVARCHAR(50)
)

CREATE TABLE MEHSUL(
ID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(50),
ALISQIYMETI FLOAT,
SATISQIYMETI FLOAT
)

CREATE TABLE SATIS(
ID INT PRIMARY KEY IDENTITY,
MEHSULID INT REFERENCES MEHSUL(ID),
ISCIID INT REFERENCES ISCI(ID),
ENDIRIM FLOAT,
SATISTARIXI DATE
)


SELECT COUNT(*) FROM ISCI

SELECT *FROM ISCI ORDER BY(MAAS) DESC

SELECT*FROM MEHSUL ORDER BY (SATISQIYMETI) DESC

SELECT*FROM SATIS ORDER BY (SATISTARIXI)

CREATE TABLE ISCIVEZIFE(
ID INT PRIMARY KEY IDENTITY,
ISCIID INT REFERENCES ISCI(ID),
VEZIFEID INT REFERENCES VEZIFE(ID)
)

INSERT INTO VEZIFE VALUES('BACKEND DEVELOPER')
INSERT INTO VEZIFE VALUES('FRONTEND DEVELOPER')
INSERT INTO VEZIFE VALUES('FULL DEVELOPER')
SELECT*FROM VEZIFE


INSERT INTO ISCI VALUES(10,'TAGHIZADE GULCHIN NAIL',1,1500)
INSERT INTO ISCI VALUES(100,'TAGHIZADE ILAHE NAIL',2,1000)
INSERT INTO ISCI VALUES(120,'TAGHIZADE NAGI NAIL',3,2500)

SELECT*FROM ISCI

